let x=2;
console.log(x);
let y=3;
y=x;
document.write(x);
alert(x);
console.log(y);
let kolyya={
   x1:2,
   lik:"dddd",
email1:true
};
console.log(kolyya);
let zuzu=confirm("Do you love zuzu?"); 
console.log(zuzu);
let all=confirm("Do youu have 18 years old?");
let isAdult=all;
console.log(all);
let DIanka={
   age:15,
   nam1:"jdjdj",
   geoup:445
};
console.log(DIanka);
console.log(typeof(age));
console.log(typeof(name1));
console.log(typeof(group));

let kaka=prompt("please enter your name","gjgjg");
let email=prompt("please email","fff");
let number=prompt("fjfjjf","fjfjf");
let ZIna=alert("your email "+ kaka+" youem fjfjf" + email + "djddj" + number);

const secminutw= 1*60;
const sechour=60*secminutw;
const secday=24*sechour;
let seccucucu=alert('fffh ' + secminutw + 'djdj ' + sechour+ 'fff ' + secday);


let x4 = 1;
let y4 = 2;
let data = String(x4);
 let res=console.log(data*         y4);
console.log(typeof res);
